data:
  audio:
    filter_conformer_conf:
      output_len_prob: 0.9
    log_mel_conf:
      n_mels: 80
      sample_rate: 16000
      window: hamming
      window_size_sec: 0.025
      window_stride_sec: 0.01
    normalize: true
    pad_token_id: 0
    spec_aug_conf:
      freq_mask_cnt: 2
      freq_mask_para: 10
      time_mask_cnt: 2
      time_mask_para: 50
    spec_sub_conf:
      max_t: 30
      num_t_sub: 3
    spec_trim_conf:
      max_t: 50
    speed_aug_conf:
      speeds: [0.9,1.0,1.1]
  text:
    bos_token_id: 2
    eos_token_id: 3
    pad_token_id: 0
model:
  ctc_reduction: sum
  ctc_weight: 0.3
  ctc_zero_inf: true
  decoder:
    attention_heads: 8
    dropout_rate: 0.1
    linear_units: 2048
    num_blocks: 3
    positional_dropout_rate: 0.1
    r_num_blocks: 3
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1
  encoder:
    activation_type: 'swish'
    attention_heads: 8
    causal: false
    cnn_module_kernel: 15
    cnn_module_norm: 'layer_norm'
    dropout_rate: 0.1
    input_layer: conv2d2
    linear_units: 2048
    normalize_before: true
    num_blocks: 12
    output_size: 256
    pos_enc_layer_type: 'rel_pos'
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    use_cnn_module: true
    use_dynamic_chunk: true
    use_dynamic_left_chunk: false
    efficient_conf:
        stride_layer_idx: [3, 7]           # layer id with StrideConv
        stride: [2, 2]                     # stride size of each StrideConv
        group_layer_idx: [3, 7]            # layer id with GroupedAttention
        group_size: 3                      # group size of every GroupedAttention layer
        stride_kernel: false               # true: recompute cnn kernels with stride
  length_normalized_loss: false
  lsm_weight: 0.1
  reverse_weight: 0.3
  vocab_size: 72
